name: Bot Emagrecer com Saúde
on:
  schedule:
    - cron: '0 12 * * 1' # Roda toda segunda-feira às 12:00 UTC
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar Dependências
        run: |
          pip install feedparser
          pip install google-auth google-api-python-client google-auth-oauthlib
          pip install google-generativeai

      - name: Rodar Bot Emagrecer com Saúde
        env:
          # Se você mudou o nome da variável no script Python, mude aqui também
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python run_bot.py

